### PR TITLE
Update jqxdocking.js

### PR DESCRIPTION
**Pull request by bekirakinci**
Added custom docking zone size option. If you add a custom width then _performPanelsLayout function is not set the width to "auto", it uses user specified width.

### CODE REVIEW

**Comment by bekirakinci** [comment]
Why did you close the pull request with any information? Can you write something about it? You couldn't do this sample before the changes...
docking

**Comment by jqwidgets** [comment]
Because your change is in violation with the product's EULA. jQWidgets is a commercial product developed only by our Team and changes are not allowed.

**Comment by bekirakinci** [comment]
Ok then please say to your development team to fix the issue...

**Comment by rofrantz** [comment]
@bekirakinci I just submitted to them also a PR with a fix but I'm curious if they ever applied yours in their code ?

**Comment by bekirakinci** [comment]
@rofrantz you can check  jqwidgets's last comment, so I left their solution, not using it more...

**Pull request closed without merging**
